Atualizando a esteira com as credenciais para Audocao

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,3 +1,12 @@
+name: Deploy Docker
+on:
+  push:
+    branches: [ "main" ] # Dispara o workflow quando houver um push na branch principal (você pode alterar)
+
+permissions:
+  pages: write
+  id-token: write
+
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
@@ -5,11 +14,20 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Debug Secrets
+        run: |
+          echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
+          echo "Token length: ${{ secrets.DOCKERHUB_TOKEN != '' && 'Token is set' || 'Token is empty' }}"
+
       - name: Login to Docker Hub
         run: |
-          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
-
+            if [[ -z "${{ secrets.DOCKERHUB_USERNAME }}" || -z "${{ secrets.DOCKERHUB_TOKEN }}" ]]; then
+              echo "Docker Hub credentials are missing. Please set them in the repository secrets."
+              exit 1
+            fi
+            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
+      
       - name: Build and push Docker image
         run: |
-          docker build -t seu-usuario/sua-imagem:${GITHUB_SHA} .
-          docker push seu-usuario/sua-imagem:${GITHUB_SHA}
+          docker buildx build -t camileite/audocao:${{ github.sha }} .
+          docker push camileite/audocao:${{github.sha}} 
